In [8]:
import numpy as np
from sklearn import datasets as ds
from sklearn import make_regression

digits = ds.load_digits()
features = digits.data
target = digits.target

features[0]

features,target,coefficients =make_regression
(n_samples=100,n_features=3,n_informative=3,n_targets=1,noise=0.0,coef=True,random_state=1)

print('Feature Matrix\n',features[:3])
print('Target Vector\n',target[:3])







SyntaxError: invalid syntax (2123319149.py, line 12)

NameError: name 'digits' is not defined

In [10]:
import pandas as pd

url = 'https://tinyurl.com/simulated_data'

dataframe = pd.read_csv(url)

dataframe.head(2)

HTTPError: HTTP Error 404: Not Found

In [11]:
import pandas as pd
from sqlalchemy import create_engine

database_connection=create_engine('sqlite:///sample.db')

dataframe=pd.read_sql_query('SELECT * FROM data',database_connection)

dataframe.head(2)

OperationalError: (sqlite3.OperationalError) no such table: data
[SQL: SELECT * FROM data]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 28, saw 412


In [18]:
import pandas as pd
import io
import requests
url="https://github.com/datasciencedojo/datasets/blob/master/titanic.csv"
s=requests.get(url).content
c=pd.read_csv(io.StringIO(s.decode('utf-8')))
c

ParserError: Error tokenizing data. C error: Expected 1 fields in line 28, saw 412


In [20]:
import pandas as pd
dataframe=pd.DataFrame()

dataframe['Name']=['Jacky Jackson','Steven Stevenson']
dataframe['Age']=[38,25]
dataframe['Driver']=[True,False]

dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [21]:
new_person=pd.Series(['Molly Mooney',40,True],index=['Name','Age','Driver'])
dataframe.append(new_person,ignore_index=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_26232\3468510024.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe.append(new_person,ignore_index=True)


Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True

In [22]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'

dataframe = pd.read_csv(url)

dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [29]:
import pandas as pd
url ='https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'

dataframe = pd.read_csv(url)
#dataframe.iloc[1:5]

#dataframe[dataframe['Sex']=='male'].head(10)

#dataframe[(dataframe['Sex']=='male') & (dataframe['Age']==25)].head(4)
#print('Maximum:',dataframe['Age'].max())
#print('Minimum:',dataframe['Age'].min())
#print('Mean:',dataframe['Age'].mean())
#print('Sum:',dataframe['Age'].sum())
#print('Count:',dataframe['Age'].count())
#dataframe.count()





In [50]:
dataframe['Sex'].unique()
dataframe['Sex'].value_counts()
dataframe['PClass'].nunique()
dataframe[dataframe['Age'].isnull()].head(3)
dataframe[dataframe['Sex']!='female'].head(2)
dataframe.drop_duplicates().head(3)
dataframe.drop_duplicates(subset=['Sex'])



Name        1313
PClass      1313
Age          756
Sex         1313
Survived    1313
SexCode     1313
dtype: int64

In [6]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'

dataframe = pd.read_csv(url)

dataframe.groupby('Sex').mean()
dataframe.groupby('Survived')['Name'].count()
dataframe.groupby(['Sex','Survived'])['Age'].mean()
dataframe.groupby(['Sex','Survived'])['Age'].count()

Sex     Survived
female  0            71
        1           217
male    0           372
        1            96
Name: Age, dtype: int64

In [7]:
import pandas as pd
import numpy as np

time_index=pd.date_range('06/06/2017',periods=100000,freq='30S')
dataframe=pd.DataFrame(index=time_index)
dataframe['Sale_Amount']=np.random.randint(1,10,100000)
dataframe.resample('W').sum()

Sale_Amount
2017-06-11        86322
2017-06-18       101307
2017-06-25       100457
2017-07-02       100349
2017-07-09       100453
2017-07-16        10248

In [8]:
dataframe.head(3)

Sale_Amount
2017-06-06 00:00:00            4
2017-06-06 00:00:30            1
2017-06-06 00:01:00            2

In [24]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
dataframe = pd.read_csv(url)

def uppercase(x):
    return x.upper()

dataframe['Name'].apply(uppercase)[0:2]



0    ALLEN, MISS ELISABETH WALTON
1     ALLISON, MISS HELEN LORAINE
Name: Name, dtype: object

In [23]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
dataframe = pd.read_csv(url)

for name in dataframe['Name'][0:2]:
    print(name.upper())

  

ALLEN, MISS ELISABETH WALTON
ALLISON, MISS HELEN LORAINE


In [26]:
import pandas as pd

url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
dataframe = pd.read_csv(url)

dataframe.groupby('Sex').apply(lambda x:x.count())

Name  PClass  Age  Sex  Survived  SexCode
Sex                                              
female   462     462  288  462       462      462
male     851     851  468  851       851      851

In [33]:
import pandas as pd

employee_data={'employee_id':['1','2','3','4'],
               'name':['Amy Jones','Allen Keys','Alice Bees',
                       'Tim Horton']}

dataframe_employees=pd.DataFrame(employee_data,columns=['employee_id','name'])

sales_data={'employee_id':['3','4','5','6'],
            'total_sales':[23456,2512,2345,1455]}
dataframe_sales=pd.DataFrame(sales_data,columns=['employee_id','total_sales'])

pd.merge(dataframe_employees,dataframe_sales,on='employee_id')
pd.merge(dataframe_employees,dataframe_sales,on='employee_id',how='outer')
pd.merge(dataframe_employees,dataframe_sales,on='employee_id',how='left')

employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0

In [3]:
import numpy as np
from sklearn import preprocessing 

feature = np.array([[-500.5], [-100.1], [0], [100.1],[900.9]])

minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))

scaled_feature=minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [6]:
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(feature)
standardized
print("Mean:",round(standardized.mean()))
print("Standard deviation:",standardized.std())

Mean: 0
Standard deviation: 1.0


In [7]:
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(feature)


array([[-2.5],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 4.5]])

In [11]:
import numpy as np
from sklearn.preprocessing import Normalizer

features = np.array([[0.5,0.5], [1.1,3.4], [1.5,20.2], [1.63,34.4], [10.9,3.3]])

#normalizer = Normalizer(norm='l2')
#normalizer.transform(features)
features_l2_norm=Normalizer(norm="l2").transform(features)
features_l2_norm
features_l1_norm=Normalizer(norm="l1").transform(features)
features_l1_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [13]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

features = np.array([[2,3],[2,3],[2,3]])

polynomial_interaction=PolynomialFeatures(degree=2,include_bias=False)
polynomial_interaction.fit_transform(features)

interaction=PolynomialFeatures(degree=2,interaction_only=True,include_bias=False)
interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [31]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

def add_five(x):
    return x+5
ten_transformer=FunctionTransformer(add_five)
ten_transformer.transform(features)

array([[7, 8],
       [7, 8],
       [7, 8]])

In [30]:
import pandas as pd

df = pd.DataFrame(features, columns=["feature_1","feature_2"])

df.apply(add_five)

feature_1  feature_2
0          7          8
1          7          8
2          7          8

In [1]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features,_=make_blobs(n_samples=10,n_features=2,centers=1,random_state=1)

features[0,0]=10000
features[0,1]=10000

outlier_detector=EllipticEnvelope(contamination=.1)
outlier_detector.fit(features)
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [2]:
feature=features[:,0]
def indicies_of_outliers(x):
    q1,q3=np.percentile(x,[25,75])
    iqr=q3-q1
    lower_bound=q1-(iqr*1.5)
    upper_bound=q3+(iqr*1.5)
    return np.where((x>upper_bound)|(x<lower_bound))

indicies_of_outliers(feature)

(array([0], dtype=int64),)

In [12]:
import pandas as pd
import numpy as np

houses = pd.DataFrame()
houses['Price']=[534433,392333,293222,4322032]
houses['Bathrooms']=[2,3.5,2,116]
houses['Square_Feet']=[1500,2500,1500,48000]

houses
houses[houses['Bathrooms']<20]
houses["Outlier"]=np.where(houses["Bathrooms"]<20,0,1)
houses
houses["Log_Of_Square_Feet"]=[np.log(x) for x in houses["Square_Feet"]]
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

In [26]:
import numpy as np
from sklearn.preprocessing import Binarizer

age=np.array([[6],[12],[20],[36],[65]])
np.digitize(age,bins=[20,30,64])
np.digitize(age,bins=[18])



array([[0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)

In [27]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

features,_=make_blobs(n_samples=50,n_features=2,centers=3,random_state=1)

dataframe=pd.DataFrame(features,columns=["feature_1","feature_2"])
clusterer=KMeans(3,random_state=0)
clusterer.fit(features)
dataframe["group"]=clusterer.predict(features)
dataframe.head()

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

In [29]:
#dropping feature containing missing value

import numpy as np
features=np.array([[1.1,11.1],[2.2,22.2],[3.3,33.3],[4.4,44.4],[np.nan,55]])

dataframe=pd.DataFrame(features,columns=["feature_1","feature_2"])
dataframe
dataframe.dropna()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

In [5]:
import numpy as np
from fancyimpute import KNN
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

features,_=make_blobs(n_samples=1000,n_features=2,random_state=1)
scaler=StandardScaler()
standardized_features=scaler.fit_transform(features)

true_value=standardized_features[0,0]
standardized_features[0,0]=np.nan

features_knn_imputed = KNN(k=5, verbose=0).fit_transform(standardized_features)
print("True Value:",true_value)
print("Imputed Value:",features_knn_imputed[0,0])



True Value: 0.8730186113995938
Imputed Value: 1.0955332713113226


In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer

feature=np.array([["Texas"],["California"],["Texas"],["Delaware"],["Texas"]])

one_hot=LabelBinarizer()
one_hot.fit_transform(feature)

pd.get_dummies(feature[:,0])

California  Delaware  Texas
0           0         0      1
1           1         0      0
2           0         0      1
3           0         1      0
4           0         0      1

In [3]:
multiclass_feature=[("Texas","Florida"),("California","Alabama"),
("Texas","Florida"),("Delware","Florida"),("Texas","Alabama")]

multi_one_hot=MultiLabelBinarizer()
multi_one_hot.fit_transform(multiclass_feature)

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [4]:
#ordinal categorical feature

import pandas as pd

dataframe=pd.DataFrame({"Score":["Low","Low","Medium","Medium","High"]})

scale_mapper={"Low":1,"Medium":2,"High":3}
dataframe['Score'].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64

In [6]:
from sklearn.feature_extraction import DictVectorizer
data_dict=[{"Red":2,"Blue":4},{"Red":4,"Blue":3},{"Red":1,"Yellow":2},{"Red":2,"Yellow":2}]
dictvectorizer=DictVectorizer(sparse=False)
features=dictvectorizer.fit_transform(data_dict)
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [7]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

X=np.array([[0,2.10,1.45],[1,1.18,1.33],[0,1.22,1.27],[1,-0.21,-1.19]])
X_with_nan=np.array([[np.nan,0.87,1.31],[np.nan,-0.67,-0.22]])

clf=KNeighborsClassifier(3,weights='distance')
trained_model=clf.fit(X[:,1:],X[:,0])

imputed_values=trained_model.predict(X_with_nan[:,1:])
X_with_imputed=np.hstack((imputed_values.reshape(-1,1),X_with_nan[:,1:]))

np.vstack((X_with_imputed,X))

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

In [8]:
#alternative
from sklearn.preprocessing import Imputer

X_complete=np.vstack((X_with_nan,X))

imputer=Imputer(strategy='most_frequent',axis=0)
imputer.fit_transform(X_complete)

ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing' (C:\Users\HP\anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

In [16]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

iris = load_iris()
features = iris.data
target = iris.target

features=features[40:,:]
target=target[40:]

target=np.where((target==0),0,1)

target

weights={0:.9,1:0.1}
RandomForestClassifier(class_weight=weights)
RandomForestClassifier(class_weight="balanced")

i_class0=np.where(target==0)[0]
i_class1=np.where(target==1)[0]

n_class0=len(i_class0)
n_class1=len(i_class1)

i_class1_downsampled=np.random.choice(i_class1,size=n_class0,replace=False)
np.hstack((target[i_class0],target[i_class1_downsampled]))
np.vstack((features[i_class0,:],features[i_class1_downsampled,:]))[0:5]

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4]])

In [10]:
import pandas as pd
import numpy as np

date_strings=np.array(['03-04-2005 11:35 PM','23-05-2010 12:01 AM','04-09-2009 09:09 PM'])
[pd.to_datetime(date,format='%d-%m-%Y %I:%M %p',errors="coerce")for date in date_strings]

[Timestamp('2005-04-03 23:35:00'),
 Timestamp('2010-05-23 00:01:00'),
 Timestamp('2009-09-04 21:09:00')]